/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as FdoRouteImport } from './routes/fdo'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunsRunIdRouteImport } from './routes/runs_.$runId'
import { Route as DepartmentsDeptRouteImport } from './routes/departments.$dept'
import { Route as ComplianceItemIdRouteImport } from './routes/compliance_.$itemId'

const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const FdoRoute = FdoRouteImport.update({
  id: '/fdo',
  path: '/fdo',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs_/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsDeptRoute = DepartmentsDeptRouteImport.update({
  id: '/departments/$dept',
  path: '/departments/$dept',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceItemIdRoute = ComplianceItemIdRouteImport.update({
  id: '/compliance_/$itemId',
  path: '/compliance/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/compliance': typeof ComplianceRoute
  '/fdo': typeof FdoRoute
  '/runs': typeof RunsRoute
  '/compliance/$itemId': typeof ComplianceItemIdRoute
  '/departments/$dept': typeof DepartmentsDeptRoute
  '/runs/$runId': typeof RunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/compliance': typeof ComplianceRoute
  '/fdo': typeof FdoRoute
  '/runs': typeof RunsRoute
  '/compliance/$itemId': typeof ComplianceItemIdRoute
  '/departments/$dept': typeof DepartmentsDeptRoute
  '/runs/$runId': typeof RunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/compliance': typeof ComplianceRoute
  '/fdo': typeof FdoRoute
  '/runs': typeof RunsRoute
  '/compliance_/$itemId': typeof ComplianceItemIdRoute
  '/departments/$dept': typeof DepartmentsDeptRoute
  '/runs_/$runId': typeof RunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/compliance'
    | '/fdo'
    | '/runs'
    | '/compliance/$itemId'
    | '/departments/$dept'
    | '/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/compliance'
    | '/fdo'
    | '/runs'
    | '/compliance/$itemId'
    | '/departments/$dept'
    | '/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/compliance'
    | '/fdo'
    | '/runs'
    | '/compliance_/$itemId'
    | '/departments/$dept'
    | '/runs_/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  ComplianceRoute: typeof ComplianceRoute
  FdoRoute: typeof FdoRoute
  RunsRoute: typeof RunsRoute
  ComplianceItemIdRoute: typeof ComplianceItemIdRoute
  DepartmentsDeptRoute: typeof DepartmentsDeptRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fdo': {
      id: '/fdo'
      path: '/fdo'
      fullPath: '/fdo'
      preLoaderRoute: typeof FdoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs_/$runId': {
      id: '/runs_/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/$dept': {
      id: '/departments/$dept'
      path: '/departments/$dept'
      fullPath: '/departments/$dept'
      preLoaderRoute: typeof DepartmentsDeptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance_/$itemId': {
      id: '/compliance_/$itemId'
      path: '/compliance/$itemId'
      fullPath: '/compliance/$itemId'
      preLoaderRoute: typeof ComplianceItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  ComplianceRoute: ComplianceRoute,
  FdoRoute: FdoRoute,
  RunsRoute: RunsRoute,
  ComplianceItemIdRoute: ComplianceItemIdRoute,
  DepartmentsDeptRoute: DepartmentsDeptRoute,
  RunsRunIdRoute: RunsRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
